### ISSUE TITLE
Netplay standard

### ISSUE THREAD

**Issue by Stinkling** [kesiev/pvp#2]
Using standard netplay with friends over wifi won't work, we've tried both of us being server and client but it won't connect.

**Comment by kesiev** [comment]
Hey, hi! I assume that you already had a look to the [Standard mode README.md section](https://github.com/kesiev/pvp/?tab=readme-ov-file#standard-mode), and you guys already have the same Room ID on client and servers and changed your _Anonymize local IPs_ Chrome settings (if you are using Chrome).

You may check if there is any firewall on your network and/or devices that is blocking WebRTC connections. If everything in your network seems okay, let me know which browsers, browser versions, and OS are you using to investigate a bit.

**Comment by Stinkling** [comment]
Thank you so much for the suggestion! I switched to a network that i knew
had no firewalls and it ran great!

**Comment by kesiev** [comment]
_Noice!_ GLHF! 🔫
